name: namaz
on:
  schedule:
    - cron: "49 * * * *"
concurrency:
  group: ci-${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  halal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        run: bash -c "$(curl -Lfs https://astral.sh/uv/install.sh)"

      - name: Run python
        run: uv run ./main.py
        env:
          TOKEN: ${{ secrets.TOK }}
